CREATE TABLE IF NOT EXISTS osrs_market.price_series(
ID MEDIUMINT NOT NULL,
updated TIMESTAMP(0) NOT NULL,
fetched TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY (ID, updated) REFERENCES osrs_market.price_update(ID, updated) ON UPDATE CASCADE,

PRIMARY KEY (ID, fetched)
);
